version: '3.7'
services:
  postgres:
    image: postgres:9.6.16-alpine
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_DB=zabbix
    volumes:
      - zabbix_db:/var/lib/postgresql/data
      - backups:/backups
    networks:
      - zabbix
    ports:
      - "5432:5432"
    deploy:
      placement:
        constraints:
          - node.labels.tipo == prod
      resources:
        limits:
          memory: 1G
          cpus: '0.50'
 
  zabbix_server:
    image: zabbix/zabbix-server-pgsql:alpine-4.4-latest
    depends_on:
      - postgres
    environment:
      - DB_SERVER_HOST=postgres
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
    volumes:
      - /etc/localtime:/etc/localtime:ro
      #- /usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
    deploy:
      placement:
        constraints:
          - node.labels.tipo == prod
      resources:
        limits:
          memory: 1G
          cpus: '0.50'
    networks:
      - zabbix
    ports:
      - "10051:10051"
    links:
      - zabbix_agente:zabbix_agente      
      
  zabbix_web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-4.4-latest
    hostname: zabbix_web
    depends_on:
      - zabbix_server
    environment:
      - DB_SERVER_HOST=postgres
      - DB_USER=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - ZBX_SERVER_HOST=zabbix_server
    ports:
      - "80:80"
    deploy:
      placement:
        constraints:
          - node.labels.tipo == prod
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - zabbix
      
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel
    volumes:
      - grafana:/var/lib/grafana
    deploy:
      placement:
        constraints:
          - node.labels.tipo == prod
      resources:
        limits:
          cpus: '0.50'
          memory: 128M
    networks:
      - zabbix
          
  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - backups:/backups
    networks:
      - zabbix      
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=zabbix
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
#     - POSTGRES_PASSWORD_FILE=/run/secrets/db_password <-- alternative for POSTGRES_PASSWORD (to use with docker secrets)
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=80
    deploy:
      placement:
        constraints:
          - node.labels.tipo == prod
      resources:
        limits:
          cpus: '0.50'
          memory: 128M     
          
volumes:
  zabbix_db:
    driver_opts:
      o: bind
      type: none
      device: /data/zabbix/postgres
  backups:
    driver_opts:
      o: bind
      type: none
      device: /data/zabbix/backup
  grafana:
    driver_opts:
      o: bind
      type: none
      device: /data/zabbix/grafana
networks:
  zabbix:
    driver: overlay